export const SCREENS = Object.freeze({
  LANDING: 'LANDING',
  GUIDELINES: 'GUIDELINES',
  ASSESSMENT: 'ASSESSMENT',
  RUNNER: 'RUNNER',
  ALREADY_COMPLETED: 'ALREADY_COMPLETED',
  SCOREBOARD: 'SCOREBOARD',
  SUBMIT_DONE: 'SUBMIT_DONE',
})
